name: pokedex-ci

run-name: Deploy to ${{ inputs.deploy_target }} by ${{ github.actor }}

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    concurrency:
      group: staging-install-dependencies
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

  # lint:
  #   needs: install-dependencies

  #   steps:
  #     - name: Run lint
  #       run: pnpm run lint

  # test:
  #   steps:
  #     - name: Run test
  #       run: pnpm run test:coverage

  # build:
  #   steps:
  #     - name: Run Build
  #       run: pnpm run build
