name: pokedex-ci

run-name: Deploy to ${{ inputs.deploy_target }} by ${{ github.actor }}

on: [push, pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run test
        run: pnpm run test
