name: pokedex-ci

run-name: Deploy to ${{ inputs.deploy_target }} by ${{ github.actor }}

on: [push]

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # - run: node --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm nx test
